### ISSUE TITLE
Android TableViews don't allow you to scroll back up

### ISSUE THREAD

**Issue by ucf713** [FokkeZB/nl.fokkezb.pullToRefresh#40]
On Android, you cannot scroll back up if you have scrolled down the table. If you try, the pull to refresh will be activated.

If I substitute a ListView in place of the TableView, it works as expected.

Code Sample:
```javascript
<Alloy>
	<Window id="homeWindow">
		<Widget id="swipeRefresh" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
        	<TableView id="table">
        	</TableView>
        </Widget>
    </Window>
</Alloy>
```

**Comment by FokkeZB** [comment]
Assuming you use the latest version, on Android it will simply wrap https://github.com/iskugor/Ti.SwipeRefreshLayout. Please check if this is a module bug (by reproducing it without the widget), because there's not much the widget could disturb really if you look at the compiled code or the controller.

**Comment by ucf713** [comment]
Looks like it is related to the module as I tested it without your widget and it has the same issue. I will let that developer know.

Thanks.
